### PR TITLE
XUnit test support and recursive method recognition

### PR DESCRIPTION
**Pull request by MelleKoning**
Hi @pver and @joshlrogers 

I merged the code from @joshlrogers forked xUnit branch, great work Josh! And I've also added the recursive lookup of XUnit test methods within the XUnit test discoverer. 

This is to support #128 

Please let me know if I missed anything.

### CODE REVIEW

**Comment by MelleKoning** [comment]
First time running the XUnit tests, properly asks for the XUnit test runner.

image

**Comment by MelleKoning** [comment]
Ok, please wait till I fixed this branch. I seem to have made a mistake in naming a folder (capitalization) and got two files or folders in github (like xUnit and XUnit) while my windows system does not see the difference.

**Comment by MelleKoning** [comment]
Ok fixed. Please review.

See notes above on the added nunit package for the xunit-console package and also the naming of the files and folders. Seems a folder is name xUnit (also in opencover.ui/master) while maybe XUnit (capital X) would have been better. 

Anyways: this will get XUnit with subclasses into the OpenCover.UI

**Comment by pver** [comment]
@MelleKoning great, thanks!
Am I correct that this completely includes the changes in the PR made by @joshlrogers?

**Comment by MelleKoning** [comment]
Hi @pver,

Yes, I first took the changes from @joshlrogers branch, so those are already included!

**Comment by pver** [comment]
Thanks for working on this @MelleKoning !

I think we can do some more sanity tests with the latest snapshot and if all looks good, we can make a new official release from the current master

**Pull request merged**
