### PR TITLE
Merge pull request #1 from OpenCoverUI/master

### PR DESCRIPTION
**Pull request by MelleKoning**
Just trying to merge main to my fork

### CODE REVIEW

**Comment by MelleKoning** [comment]
Ok few things: I merged down latest changes first to myFork, than fixed the NUnit Discoverer to find the NameSpace name via DeclaringType. Have also added the XUnit framework (2.1.0 stable version). The xUnit discover tests are still ignored though. But it's good that we now have proper namespace for nested classes found in both MSTest and NUnit :)

**Comment by pver** [comment]
Looks like we run into a similar issue as described here: https://github.com/xunit/xunit/issues/261

I'll see what we can do for this. We can probably fix it by updating the nuget.exe included in the src folder (https://github.com/OpenCoverUI/OpenCover.UI/blob/master/.nuget/NuGet.exe) altough I noticed there's an approach without including NuGet.exe in our source at all (https://www.appveyor.com/blog/2014/03/18/about-nuget-package-restore/) I'll do some tests with this tomorrow

**Comment by pver** [comment]
Hi @MelleKoning , I think the nuget issue should be fixed (I removed nuget from source control, so it should now use the newer version on AppVeyor). Could you try to merge it in your master? It should trigger a new check on appveyor and hopefully fix the build error you get.

**Comment by MelleKoning** [comment]
Hi @pver yes, seems AppVeyor is happy now.

**Comment by pver** [comment]
Thanks @MelleKoning, looks great! I'll merge this in

**Pull request merged**
